mixed-port: 7890
redir-port: 7892
allow-lan: true
mode: rule
log-level: info
external-controller: '127.0.0.1:9090'
dns:
    enable: true
    ipv6: false
    listen: 0.0.0.0:53
    enhanced-mode: redir-host
    fake-ip-range: 198.18.0.1/16
    use-hosts: true
    nameserver:
        - 114.114.114.114
        - 223.5.5.5
        - 119.29.29.29
    fallback:
        - 8.8.8.8
        - 1.1.1.1
        - 208.67.222.222
    fallback-filter:
        geoip: true
        ipcidr:
            - 240.0.0.0/4
