port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
dns:
    enable: true
    enhanced-mode: redir-host
    nameserver:
        - 223.5.5.5
        - 119.29.29.29
        - 8.8.8.8
        - 1.1.1.1
        - 208.67.222.222
tun:
  enable: true
  stack: system
  dns-hijack:
    - 8.8.8.8 # 可任意设置，但为了保证CFW关闭后能不影响联网，建议设置真实能访问的DNS服务器
  auto-route: true
  auto-detect-interface: true
